version: "3"
services:
  backend:
    container_name: backend
    build:
        context: ./
        dockerfile: dockerfile.backend
    image: backend:latest
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      MYSQL_DB_HOST: host.docker.internal # equivalent to localhost
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
      MYSQL_DB_USER: ${MYSQL_DB_USER}
      MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
